### ISSUE TITLE
наложение формы выбора категории инвалидности

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/social-navigator#29]
открыть форму, нажать кнопку обновления и сразу перейти на карту: на карте отображается контент из формы выбора.

**Comment by petrsudevel** [comment]
а может убрать из меню выбора категорий инвалидности кнопку обновить?
она там вроде как не нужна а если убрать то ошибка исчезнет

**Comment by petrsudevel** [comment]
исправил кнопку, теперь эта ошибка возникает только если успеть открыть меню и перейти в нем на карту или на любое другое окно

**Comment by petrsudevel** [comment]
по поводу кнопки баг на ней еще можно поймать если во время обновления очень быстро кликать мышкой по кнопке перехода на карту и успеть когда флаг апдейта уже сбросился а апдейт еще не завершился (флаг выставляется какойто стандартной ф-ей андройда и исправить это я немогу), однако на практике с сенсорным экраном поймать эту ошибку таким образом практически нереально (ну я так считаю).

**Comment by petrsudevel** [comment]
убрал кнопку обновить теперь ошибку непоймать
